" Make Vim follows XDG
" inspired by https://github.com/kaleb/vim-files/blob/master/xdg.vim

if empty($XDG_CACHE_HOME)
        let $XDG_CACHE_HOME = $HOME.'/.cache'
endif
if empty($XDG_CONFIG_HOME)
        let $XDG_CONFIG_HOME = $HOME.'/.config'
endif
if empty($XDG_DATA_HOME)
        let $XDG_DATA_HOME = $HOME.'/.local/share'
endif

set runtimepath-=~/.vim
set runtimepath^=$XDG_DATA_HOME/vim
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath-=~/.vim/after
set runtimepath+=$XDG_DATA_HOME/vim/after
set runtimepath+=$XDG_CONFIG_HOME/vim/after

let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
source $XDG_CONFIG_HOME/vim/vimrc
